library(tidyverse)
library(janitor) # tabyl
library(ggplot2)

# download tabs-delimited .txt clonotype files from K-drive
# compile clonotype files across samples of the same antigen (and maybe across different antigens ?)
# or need to separate compiled clonotype files by antigen ??


# specify clonotype txt file (generated by MiXCR) path
clonotype_path = "C:/Users/apoca/Documents/TCRseq/MiXCR_Results/txt_files"

# get filenames of all clonotype txt file
clonotype_files = dir(path = clonotype_path, pattern = "*.clonotypes.ALL.txt")

# get all tables into 1 nice table
dat <- clonotype_files %>%
  map( function(x){ # return a list of tables
    read_delim( file.path(clonotype_path, x), delim = "\t" ) %>%
      select( cloneCount, cloneFraction, targetSequences, targetQualities, minQualCDR3, aaSeqCDR3 ) %>% # keep specific columns
      mutate(
        antigen = strsplit(x, "-", fixed = T)[[1]][1],
        sample = paste0( "S-", strsplit(strsplit(x, "_", fixed = T)[[1]][1], "-", fixed = T)[[1]][2] ),
        # rev_cumsum = rev( cumsum( rev(cloneFraction) ) ), # cumulative clone fraction from bottom row to top row
        cumsum_cloneFrac = cumsum( cloneFraction ) # cumulative clone fraction from top row to bottom row
      ) %>%
      select(antigen, sample, cloneCount, cloneFraction, cumsum_cloneFrac, aaSeqCDR3, everything()) # rearrange columns
  } ) %>% 
  reduce(rbind) # reduce(append) lists of tables into a table 


# memory size of data table
print(object.size(dat), units = "GB")


# No NA
dat %>% 
  select_if(function(x) any(is.na(x))) %>% 
  summarise_each(~sum(is.na(.)))


# how many rows (unique targetSequences) for each sample
dat %>%
  group_by(antigen, sample) %>%
  summarize(
    sum_cloneCounts = sum(cloneCount), 
    unique_targetSeq_counts = length(unique(targetSequences)), # equal to nrows=n()
    unique_aaSeqCDR3_counts = length(unique(aaSeqCDR3))
  ) 

# are targetSequences unique within each sample?  YES!
# are aaSeqCDR3 unique within each sample?  NO! -- not surprising since different triplicates in reading frame translated to same aa?


#--------------------------------------------------------------------------------------------------------------
# investigate PosCont 
# run with control RNAs that came with sequencing kit -- just to show sequencing works

dat %>% filter(antigen == "PosCont", sample == "S-1") %>% head()

dat %>% filter(antigen == "PosCont", sample == "S-2") %>% head()

# check these numbers with the company's sequencing kit manual/handbook?

# remove positive controls?

dat <- dat %>% filter(antigen != "PosCont")

# Now, how many rows for each sample
dat %>% group_by(antigen, sample) %>% tally()
  

#--------------------------------------------------------------------------------------------------------------
# investigate NegCont
# run withOUT RNA 
# use this as measure of background noise or to indicate any RNA contamination?

dat %>% filter(antigen == "NegCont", sample == "S-1") %>% head()

dat %>% filter(antigen == "NegCont", sample == "S-2") %>% head()

# Note that NegCont2 have very few target sequences, so clone counts of 45 and 20 will give high cloneFraction ?


# filter NegCont only
NegCont <- dat %>% filter(antigen == "NegCont")


# NegCont's counts of targetSequences at different thresholds
map(c(.01, .007, .006, .005, .001, .0001), ~ nrow(filter(NegCont, sample == "S-1", cloneFraction > .))) %>% unlist() %>%
  set_names(nm = paste0(c(.01, .007, .006, .005, .001, .0001)*100,"%"))


# Any NegCont targetSequences with kinda high cloneFrac? They are all supposed to be small?
NegCont %>% filter(cloneFraction > 0.01)
NegCont %>% filter(cloneFraction > 0.007)


# NegCont_S-2 has small number of targetSequences, cloneFrac high even with cloneCount = 2
# NegCont_S-1 only has 1 targetSeq with cloneFraction slightly higher than 0.01, the rest lower than that
# Is cloneFraction = 0.01 ie. 1% good cutoff? 
# maybe also check targetQualities when cloneFraction is low   


# filter non-NegCont samples
dat_ex_NegCont <- dat %>% filter(antigen != "NegCont")
dat_ex_NegCont %>% group_by(antigen, sample) %>% tally() # check
nrow(dat_ex_NegCont) # in total 12663 rows


# do targetSequences of non-NegCont samples have their counterparts in NegCont data?
length( which( dat_ex_NegCont$targetSequences %in% NegCont$targetSequences ) ) 
length( which( NegCont$targetSequences %in% dat_ex_NegCont$targetSequences ) ) 
# about half of targetSequences (6572 out of 12663 rows) among non-NegCont samples have counterparts in NegCont data


# check clone fraction distribution among those non-negative samples with targetSequences that also appear in negative controls
# dat_ex_NegCont %>%
#   filter(targetSequences %in% NegCont$targetSequences) %>%
#   group_by(antigen, sample) %>%
#   summarize(
#     targetSeq_counts = n(),
#     maximum_cloneFrac = round(max(cloneFraction),4),
#     maximum_cloneCount = max(cloneCount)
#   ) %>% arrange(desc(targetSeq_counts))
dat_ex_NegCont %>%
  filter(targetSequences %in% NegCont$targetSequences) %>%
  group_by(antigen, sample) %>%
  summarize(
    targetSeq_counts = n(),
    maximum_cloneFrac = round(max(cloneFraction),4),
    maximum_cloneCount = max(cloneCount)
  ) %>% ungroup() %>% mutate(
    targetSeq_percent = targetSeq_counts / (dat_ex_NegCont %>% group_by(antigen, sample) %>% tally() %>% pull(n))
  ) %>% select(-targetSeq_counts) %>% 
  arrange(desc(maximum_cloneFrac))


# check clone fraction distribution among those non-negative samples with targetSequences that do NOT appear in negative controls
dat_ex_NegCont %>%
  filter(!(targetSequences %in% NegCont$targetSequences)) %>%
  group_by(antigen, sample) %>%
  summarize(
    targetSeq_counts = n(),
    maximum_cloneFrac = round(max(cloneFraction),4),
    maximum_cloneCount = max(cloneCount)
  ) %>% arrange(desc(targetSeq_counts))


#--------------------------------------------------------------------------------------------------------------
# investigate overall distribution of cloneFraction exlcuding NegCont

prcntile <- c(.95, .97, .98, .99, .995)

summary(dat_ex_NegCont$cloneFraction)
quantile(dat_ex_NegCont$cloneFraction, probs = prcntile)
round(ecdf(dat_ex_NegCont$cloneFraction)(c(0.0001, 0.001, 0.01)), 4)
# 95.5% of "target sequences" have clone fraction lower than 0.1%
# 98.66% of "target sequences" have clone fraction lower than 1%
# a lot of background noise?


# c(.95, .975, .99, .995, .999)-quantiles of clone fraction for each sample
dat_ex_NegCont %>%
  group_by(antigen, sample) %>%
  summarize_at( vars(cloneFraction), map( prcntile, ~ partial(quantile, probs = .x) ) %>%
                  set_names( nm = paste0("cloneFrac_", prcntile*100,"%") ) ) %>%
  add_column(seq_counts = dat_ex_NegCont %>% group_by(antigen, sample) %>% tally() %>% pull(n)) %>%
  select(antigen, sample, seq_counts, everything())


# cumulative cloneFraction for top 15 sequences (in terms of highest cloneFraction) for each sample
dat_ex_NegCont %>%
  group_by(antigen, sample) %>%
  top_n(15, cloneFraction) %>%
  select(antigen, sample, cumsum_cloneFrac) %>%
  mutate(
    cumsum_cloneFrac = round(cumsum_cloneFrac,3), 
    sequence = paste0("seq_",row_number())
    ) %>%
  pivot_wider(names_from = sequence, values_from = cumsum_cloneFrac) %>%
  add_column(seq_counts = dat_ex_NegCont %>% group_by(antigen, sample) %>% tally() %>% pull(n)) %>%
  select(antigen, sample, seq_counts, seq_1:seq_15)

cumcloneFrac_topSeq_df <- dat_ex_NegCont %>%
  group_by(antigen, sample) %>%
  top_n(10, cloneFraction) %>%
  top_n(1, cumsum_cloneFrac) %>%
  mutate( cumsum_cloneFrac = round(cumsum_cloneFrac,4) ) %>%
  unite(antigen_sample, antigen, sample, sep = "_", remove = T) %>%
  select(antigen_sample, cumsum_cloneFrac) 

ggplot(data = cumcloneFrac_topSeq_df, aes(x = reorder(antigen_sample, -cumsum_cloneFrac), y = cumsum_cloneFrac)) +
  geom_bar(stat = "identity", fill = "steelblue", width = 0.5) +
  coord_cartesian(ylim=c(0, 1.1)) +
  geom_text( aes(label = paste0(cumsum_cloneFrac*100,"%","\n(n=",
                                dat_ex_NegCont %>% group_by(antigen, sample) %>% summarize(n = sum(cloneCount)) %>% pull(n),")")), 
             vjust=-0.3, size=3 ) +
  labs(x = "antigen_sample", y = "cumulative clone fraction",
       title = "Cumulative clone fraction for top 10 sequences of each sample
       (n = total number of clones for each sample)") +
  theme(plot.title = element_text(hjust = 0.5),
        axis.text.x=element_text(angle=45, hjust=1))


# cloneFraction for top 15 sequences (in terms of highest cloneFraction) for each sample
dat_ex_NegCont %>%
  group_by(antigen, sample) %>%
  top_n(15, cloneFraction) %>%
  select(antigen, sample, cloneFraction) %>%
  mutate(
    sequence = paste0("seq_",row_number())
  ) %>%
  pivot_wider(names_from = sequence, values_from = cloneFraction) %>%
  add_column(seq_counts = dat_ex_NegCont %>% group_by(antigen, sample) %>% tally() %>% pull(n)) %>%
  select(antigen, sample, seq_counts, seq_1:seq_15)

cloneFrac_topSeq_df <- dat_ex_NegCont %>%
  group_by(antigen, sample) %>%
  top_n(10, cloneFraction) %>%
  mutate( sequence = paste0("seq_",row_number()),
          sequence = factor(sequence, levels = paste0("seq_",1:10))) %>% 
  unite(antigen_sample, antigen, sample, sep = "_", remove = T) %>%
  select(antigen_sample, sequence, cloneFraction) %>%
  filter(sequence %in% paste0("seq_", 1:10) )

ggplot(cloneFrac_topSeq_df, aes(x=sequence, y=cloneFraction, group=antigen_sample)) +
  geom_line(aes(color=antigen_sample)) +
  geom_point(aes(color=antigen_sample)) +
  labs(title = "Clone fraction for top 10 sequences of each sample") +
  theme(plot.title = element_text(hjust = 0.5),
        axis.text.x=element_text(angle=45, hjust=1))

cloneFrac_topSeq_df2 <- dat_ex_NegCont %>%
  group_by(antigen, sample) %>%
  top_n(3, cloneFraction) %>%
  mutate( sequence = paste0("seq_",row_number()),
          sequence = factor(sequence, levels = paste0("seq_",1:10))) %>% 
  unite(antigen_sample, antigen, sample, sep = "_", remove = T) %>%
  select(antigen_sample, sequence, cloneFraction) %>%
  group_by(antigen_sample) %>% 
  mutate(mx = max(cloneFraction)) %>% 
  arrange(desc(mx), desc(cloneFraction)) 

ggplot(cloneFrac_topSeq_df2, aes(x=reorder(antigen_sample, -mx), y=cloneFraction, fill=sequence)) +
  geom_bar(stat="identity", position=position_dodge()) +
  geom_text( aes(label = paste0(round(cloneFraction*100,1),"%")), position = position_dodge(0.9), vjust=-0.3, size=2.5 ) +
  labs(x = "antigen_sample", title = "Clone fraction for top 3 sequences of each sample") +
  theme(plot.title = element_text(hjust = 0.5),
        axis.text.x=element_text(angle=45, hjust=1),
        legend.position = "bottom")


#--------------------------------------------------------------------------------------------------------------
# investigate minQualCDR3 -- score of sequence qualities ?
# low cloneFraction may indicate background noise which may be reflected with lower targetQualities ?
# probably good to disregard very weak signal with bad target qualities ?

dat %>% 
  tabyl(minQualCDR3) %>% 
  adorn_pct_formatting() %>%
  map_df(rev)
# maximum quality score of 38
# 15.4% of target sequences have quality score lower than 38 -- are these sequences with low clone fraction?
# for each sample, should we throw away thse "subpar" sequences (and all the sequences below them) ?  

lower_quality <- dat %>% 
  filter(minQualCDR3 < 38) %>% # extract rows with minQualCDR3 < 38
  group_by(antigen, sample) %>%
  # top_n(1, minQualCDR3) %>%
  # top_n(1, cloneFraction) %>% # keep row with highest cloneFraction among those with minQualCDR3 < 38 for each sample
  top_n(-1, cumsum_cloneFrac) %>% # keep row with smallest cumulative cloneFraction among those with minQualCDR3 < 38 for each sample
  ungroup()
lower_quality
# preferably all rows in lower_quality to have low cloneFraction & high cumsum of cloneFraction, indicating only noises have lower CDR3 quality
# AR811_S-5 & Pap19_S-5 have low cloneFraction but also low cumsum_cloneFrac
# indicating something weird about the target sequences for these samples?


dat_ex_NegCont %>% 
  tabyl(minQualCDR3) %>% 
  adorn_pct_formatting() %>%
  map_df(rev) %>%
  rename(targetSeq_counts = n)

minQual_df <- dat_ex_NegCont %>% 
  tabyl(minQualCDR3) %>% 
  map_df(rev) %>%
  mutate(percent = ifelse(minQualCDR3 <= 33, sum(percent[minQualCDR3 <= 33]), percent)) %>%
  select(minQualCDR3, percent) %>%
  filter(minQualCDR3 >= 33) %>%
  mutate(minQualCDR3 = as.character(minQualCDR3),
         minQualCDR3 = ifelse(minQualCDR3 == 33, "33 and below", minQualCDR3),
         minQualCDR3 = factor(minQualCDR3, levels = c(38:34,"33 and below")))

ggplot(data=minQual_df, aes(x=minQualCDR3, y=percent)) +
  geom_bar(stat="identity", fill="steelblue")+
  geom_text(aes(label=paste0(round(percent,4)*100, "%")), vjust=-.3, size=3.5)+
  labs(title = "Percentage of targetSequences among non-negative-control samples with their quality scores") +
  theme(plot.title = element_text(hjust = 0.5))


minQual_df2 <- dat_ex_NegCont %>% 
  filter(minQualCDR3 < 38) %>% # extract rows with minQualCDR3 < 38
  group_by(antigen, sample) %>%
  top_n(-1, cumsum_cloneFrac) %>% # keep row with smallest cumulative cloneFraction among those with minQualCDR3 < 38 for each sample
  unite(antigen_sample, antigen, sample, sep = "_", remove = T) %>%
  select(antigen_sample, cloneCount, cloneFraction, minQualCDR3) %>%
  arrange(desc(cloneFraction))
  

summary(lower_quality$cloneFraction)
table(lower_quality$cloneFraction)
lower_quality[lower_quality$cloneFraction ==max(lower_quality$cloneFraction),]


#--------------------------------------------------------------------------------------------------------------
# Decide what cutoff to remove "background-noise" sequences

# cloneFrac_cutoff <- 0.0001 # clone fraction for each targetSequence must be above 0.01%
# cloneCount_cutoff <- 2 # every targetSequence must have more than 2 clones
cloneFrac_cutoff <- 0 # no cutoff
cloneCount_cutoff <- 0 # no cutoff

dat_cutoff <- dat_ex_NegCont %>% 
  filter(cloneFraction > cloneFrac_cutoff, cloneCount > cloneCount_cutoff) %>% 
  select(-targetQualities)

# some summary data after cutoff
dat_cutoff %>% group_by(antigen, sample) %>% 
  mutate(
    targetSeq_counts = n(),
    minQual = min(minQualCDR3)
  ) %>% top_n(1, cumsum_cloneFrac) %>%
  select(antigen, sample, cumsum_cloneFrac, targetSeq_counts, minQual) %>%
  arrange(desc(cumsum_cloneFrac))



#--------------------------------------------------------------------------------------------------------------
# overall target sequence comparison 

dat_cutoff <- dat_cutoff %>%
  unite(antigen_sample, antigen, sample, sep = "_", remove = F)

targetSeq_summary <- dat_cutoff %>%
  tabyl(targetSequences, antigen_sample) %>%
  adorn_totals("col") %>%
  arrange(desc(Total)) %>%
  filter(Total >= 2)


# compare samples from certain antigen(s)
antigen_compare <- function(ANTIGEN){
  targetSeq_summary %>% 
    select(contains(ANTIGEN)) %>%
    mutate(sum = rowSums(.) ) %>%
    add_column(targetSequences = targetSeq_summary %>% pull(targetSequences)) %>%
    select(targetSequences, sum) %>% 
    arrange(desc(sum)) %>%
    filter(sum > 1)
}

# same antigen comparison 
antigen_compare("AR805")
antigen_compare("PAP11")
antigen_compare("PAP13")
antigen_compare("PAP19")

# more antigen comparison appearing in any one sample belonging to any one of the specified antigen(s)
antigen_compare(c("PAP11", "PAP13", "PAP19"))
antigen_compare(c("AR805", "AR811"))
antigen_compare(c("AR811", "PAP11", "PAP13"))

# more specific antigen_sample comparison
antigen_compare(c("AR811_S-5", "PAP19_S-5"))
antigen_compare(c("SSX2103_S-5", "SSX241_S-4"))


# antigen-specific only 
# antigen_compare_specific <- function(ANTIGEN){
#   targetSeq_summary %>%
#     filter(Total ==2) %>%
#     filter_at(vars(contains(ANTIGEN)), ~ . == 1) 
#   }

# same antigen comparison 
# antigen_compare_specific("AR805")
# antigen_compare_specific("PAP11")
# antigen_compare_specific("PAP13")
# antigen_compare_specific("PAP19")


# we want to know cloneFraction in summary too

nonzero_index <- which( subset(targetSeq_summary, select = -Total) == 1, arr.ind = T )
summary_cloneFrac <- targetSeq_summary

# Now, replace the ones with their cloneFrac
# maybe a more efficient coding than this?

for (i in 1: nrow(nonzero_index)){
  ant_samp <- colnames(targetSeq_summary)[ nonzero_index[i,]['col'] ]
  targ_seq <- targetSeq_summary$targetSequences[ nonzero_index[i,]['row'] ]
  summary_cloneFrac[ nonzero_index[i,]['row'] , nonzero_index[i,]['col'] ] <- 
    dat_cutoff$cloneFraction[ dat_cutoff$antigen_sample == ant_samp & dat_cutoff$targetSequences == targ_seq ]
}

summary_cloneFrac <- summary_cloneFrac %>%
  mutate(
    sum_cloneFrac = rowSums( subset(summary_cloneFrac, select = -c(targetSequences, Total)) )
  ) %>%
  rename(nonzero_counts = Total) %>%
  arrange(desc(nonzero_counts), desc(sum_cloneFrac)) %>%
  left_join( dat_cutoff %>% select(targetSequences,aaSeqCDR3) %>% distinct(targetSequences,aaSeqCDR3), by = "targetSequences" ) %>%
  select(targetSequences, aaSeqCDR3, everything())


# antigen-specific only 
antigen_compare_specific <- function(ANTIGEN){
  summary_cloneFrac %>%
    filter(nonzero_counts ==2) %>%
    filter_at(vars(contains(ANTIGEN)), ~ . >0) 
}

# same antigen comparison 
antigen_compare_specific("AR805")
antigen_compare_specific("PAP11")
antigen_compare_specific("PAP13")
antigen_compare_specific("PAP19")


# bar-plot each row of summary_cloneFrac

barplot_func <- function(row){
  barplot_df <- subset(summary_cloneFrac, select = -c(nonzero_counts, sum_cloneFrac))[row,] 
  barplot_title <- paste0("targetSequence = ", barplot_df$targetSequences, 
                          "\naaSeqCDR3 = ", barplot_df$aaSeqCDR3)
  
  barplot_df <- barplot_df %>%
    select(-c(targetSequences, aaSeqCDR3)) %>%
    pivot_longer(everything(), names_to = "antigen_sample", values_to = "clone_fraction") %>%
    # mutate(clone_fraction = round(clone_fraction,4)) %>%
    filter(clone_fraction > 0) 
  
  ggplot(data = barplot_df, aes(x = reorder(antigen_sample, -clone_fraction), y = clone_fraction)) +
    geom_bar(stat = "identity", fill = "steelblue", width = 0.3) +
    geom_text(aes(label = paste0(round(clone_fraction*100,4),"%")), vjust=-0.3, size=3) +
    labs(x = "antigen_sample", title = barplot_title) +
    theme(plot.title = element_text(hjust = 0.5, size = 8),
          axis.text.x=element_text(angle=45, hjust=1))
}

barplot_func(3)

barplot_ind <- which(summary_cloneFrac$targetSequences %in% antigen_compare_specific("PAP13")$targetSequences) 
barplot_func( barplot_ind[1] )
