library(tidyverse)
library(stringr) # strsplit
library(janitor) # tabyl

# download tabs-delimited .txt clonotype files from K-drive
# compile clonotype files across samples of the same antigen (and maybe across different antigens ?)
# or need to separate compiled clonotype files by antigen ??


# specify clonotype txt file (generated by MiXCR) path
clonotype_path = "C:/Users/apoca/Documents/TCRseq/MiXCR_Results/txt_files"

# get filenames of all clonotype txt file
clonotype_files = dir(path = clonotype_path, pattern = "*.clonotypes.ALL.txt")

# get all tables into 1 nice table
dat <- clonotype_files %>%
  map( function(x){ # return a list of tables
    read_delim( file.path(clonotype_path, x), delim = "\t" ) %>%
      select( cloneCount, cloneFraction, targetSequences, targetQualities, minQualCDR3, aaSeqCDR3 ) %>% # keep specific columns
      mutate(
        antigen = strsplit(x, "-", fixed = T)[[1]][1],
        sample = paste0( "S-", strsplit(strsplit(x, "_", fixed = T)[[1]][1], "-", fixed = T)[[1]][2] ),
        # rev_cumsum = rev( cumsum( rev(cloneFraction) ) ), # cumulative clone fraction from bottom row to top row
        cumsum = cumsum( cloneFraction ) # cumulative clone fraction from top row to bottom row
      ) %>%
      select(antigen, sample, cloneCount, cloneFraction, cumsum, aaSeqCDR3, everything()) # rearrange columns
  } ) %>% 
  reduce(rbind) # reduce(append) lists of tables into a table 

# memory size of data table
print(object.size(dat), units = "GB")


# how many rows for each sample
dat %>%
  group_by(antigen, sample) %>%
  summarize(
    nrows = n(), 
    unique_targetSeq_counts = length(unique(targetSequences)),
    unique_aaSeqCDR3_counts = length(unique(aaSeqCDR3))
  ) 

# are targetSequences unique within each sample?  YES!
# are aaSeqCDR3 unique within each sample?  NO!


#--------------------------------------------------------------------------------------------------------------
# investigate PosCont 
# run with control RNAs that came with sequencing kit -- just to show sequencing works

dat %>% filter(antigen == "PosCont", sample == "S-1") %>% head()

dat %>% filter(antigen == "PosCont", sample == "S-2") %>% head()

# check these numbers with the company's sequencing kit manual/handbook?

# remove positive controls?

dat <- dat %>% filter(antigen != "PosCont")

# Now, how many rows for each sample
dat %>% group_by(antigen, sample) %>% tally()
  

#--------------------------------------------------------------------------------------------------------------
# investigate NegCont
# run withOUT RNA 
# use this as measure of background noise or to indicate any RNA contamination?

dat %>% filter(antigen == "NegCont", sample == "S-1") %>% head()

dat %>% filter(antigen == "NegCont", sample == "S-2") %>% head()

# Note that NegCont2 have very few target sequences, so clone counts of 45 and 20 will give high cloneFraction ?


# filter NegCont only
NegCont <- dat %>% filter(antigen == "NegCont")


# filter non-NegCont samples
dat_ex_NegCont <- dat %>% filter(antigen != "NegCont")
dat_ex_NegCont %>% group_by(antigen, sample) %>% tally() # check
nrow(dat_ex_NegCont) # in total 12663 rows


# do targetSequences of non-NegCont samples have their counterparts in NegCont data?
length( which( dat_ex_NegCont$targetSequences %in% NegCont$targetSequences ) ) 
length( which( NegCont$targetSequences %in% dat_ex_NegCont$targetSequences ) ) 
# about half of targetSequences (6572 out of 12663 rows) among non-NegCont samples have counterparts in NegCont data


summary(dat$cloneFraction[dat$antigen=="NegCont"])
summary(dat$cloneFraction[dat$antigen=="NegCont" & dat$cloneFraction < 0.05])
hist(dat$cloneFraction[dat$antigen=="NegCont" & dat$cloneFraction < 1E-4])


#--------------------------------------------------------------------------------------------------------------
# investigate overall distribution of cloneFraction

prcntile <- c(.95, .975, .99, .995, .999)

summary(dat$cloneFraction)
quantile(dat$cloneFraction, probs = prcntile)
ecdf(dat$cloneFraction)(0.001) 
# 99.7% of "target sequences" have clone fraction lower than 0.1%
# a lot of background noise?


# c(.95, .975, .99, .995, .999)-quantiles of clone fraction for each sample
dat %>%
  group_by(antigen, sample) %>%
  summarize_at( vars(cloneFraction), map( prcntile, ~ partial(quantile, probs = .x) ) %>%
                  set_names( nm = paste0("cloneFrac_", prcntile*100,"%") ) ) %>%
  add_column(seq_counts = dat %>% group_by(antigen, sample) %>% tally() %>% pull(n)) %>%
  select(antigen, sample, seq_counts, everything())


# cumulative cloneFraction for top 10 sequences (in terms of highest cloneFraction) for each sample
dat %>%
  group_by(antigen, sample) %>%
  top_n(10, cloneFraction) %>%
  select(antigen, sample, cumsum) %>%
  mutate(
    cumsum = round(cumsum,3), 
    sequence = paste0("seq_",row_number())
    ) %>%
  pivot_wider(names_from = sequence, values_from = cumsum) %>%
  add_column(seq_counts = dat %>% group_by(antigen, sample) %>% tally() %>% pull(n)) %>%
  select(antigen, sample, seq_counts, seq_1:seq_10)


#--------------------------------------------------------------------------------------------------------------
# investigate minQualCDR3 -- score of sequence qualities?

dat %>% 
  tabyl(minQualCDR3) %>% 
  adorn_pct_formatting() %>%
  map_df(rev)
# maximum quality score of 38
# 15.4% of target sequences have quality score lower than 38 -- are these sequences with low clone fraction?
# for each sample, should we throw away thse "subpar" sequences (and all the sequences below them) ?  

lower_quality <- dat %>% 
  filter(minQualCDR3 < 38) %>% # extract rows with minQualCDR3 < 38
  group_by(antigen, sample) %>%
  # top_n(1, minQualCDR3) %>%
  # top_n(1, cloneFraction) %>% # keep row with highest cloneFraction among those with minQualCDR3 < 38 for each sample
  top_n(-1, cumsum) %>% # keep row with smallest cumulative cloneFraction among those with minQualCDR3 < 38 for each sample
  ungroup()
lower_quality
# preferably all rows in lower_quality to have high cumsum of cloneFraction, indicating only noises have lower CDR3 quality
# AR811-5_S1, NegCont-1_S6, Pap19-5_S5, PosCont-1_S7 have low cloneFraction but also low cumsum
# indicating something weird about the target sequences for these samples?


summary(lower_quality$cloneFraction)
table(lower_quality$cloneFraction)
lower_quality[lower_quality$cloneFraction ==max(lower_quality$cloneFraction),]


#--------------------------------------------------------------------------------------------------------------
# Decide what cutoff to remove "background-noise" sequences




#--------------------------------------------------------------------------------------------------------------
# pairwise comparison 

# compare clone fraction



#--------------------------------------------------------------------------------------------------------------
# overall target sequence comparison 

